/** @type {import('tailwindcss').Config} */
import { uiColorTokens } from "./src/styles/uiColorTokens.ts";

export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        jazz: ["Lets Jazz", "sans-serif"],
      },
      colors: {
        // UI Color Tokens for consistent design system
        ui: uiColorTokens,
        // Musical colors are dynamically generated by the unified color system
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        float: "float 6s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};
