// Music Theory Data for Emotitone Solfege
// Contains all the static data structures for scales, solfege, and patterns

import type {
  SolfegeData,
  Scale,
  MelodicPattern,
  ChromaticNote,
} from "@/types/music";

// Helper function to generate CSS variable references
function getCSSVar(varName: string): string {
  return `var(--${varName})`;
}

// Re-export types for backward compatibility
export type { SolfegeData, Scale, MelodicPattern, ChromaticNote };

// The 12 chromatic notes
export const CHROMATIC_NOTES: ChromaticNote[] = [
  "C",
  "C#",
  "D",
  "D#",
  "E",
  "F",
  "F#",
  "G",
  "G#",
  "A",
  "A#",
  "B",
];

// Major scale solfege data with emotional descriptions and colors
export const MAJOR_SOLFEGE: SolfegeData[] = [
  {
    name: "Do",
    number: 1,
    emotion: "Home, rest, stability",
    description: "The foundation. Complete resolution.",
    colorGradient: getCSSVar("solfege-do-major-gradient"),
    colorPrimary: getCSSVar("solfege-do-major-primary"),
    colorSecondary: getCSSVar("solfege-do-major-secondary"),
    colorAccent: getCSSVar("solfege-do-major-accent"),
    colorHighlight: getCSSVar("solfege-do-major-highlight"),
    colorFlecks: getCSSVar("solfege-do-major-flecks"),
    fleckShape: "circle",
    texture: "foundation, trust, warmth from peace",
  },
  {
    name: "Re",
    number: 2,
    emotion: "Forward motion, stepping up",
    description: "Moving away from home with purpose.",
    colorGradient: getCSSVar("solfege-re-major-gradient"),
    colorPrimary: getCSSVar("solfege-re-major-primary"),
    colorSecondary: getCSSVar("solfege-re-major-secondary"),
    colorAccent: getCSSVar("solfege-re-major-accent"),
    colorHighlight: getCSSVar("solfege-re-major-highlight"),
    colorFlecks: getCSSVar("solfege-re-major-flecks"),
    fleckShape: "mist",
    texture: "hopeful lift, gentle curiosity",
  },
  {
    name: "Mi",
    number: 3,
    emotion: "Bright, joyful optimism",
    description: "Sunny and optimistic, wants to rise.",
    colorGradient: getCSSVar("solfege-mi-major-gradient"),
    colorPrimary: getCSSVar("solfege-mi-major-primary"),
    colorSecondary: getCSSVar("solfege-mi-major-secondary"),
    colorAccent: getCSSVar("solfege-mi-major-accent"),
    colorHighlight: getCSSVar("solfege-mi-major-highlight"),
    colorFlecks: getCSSVar("solfege-mi-major-flecks"),
    fleckShape: "sparkle",
    texture: "clarity and rising joy",
  },
  {
    name: "Fa",
    number: 4,
    emotion: "Tension, unease",
    description: "Unstable, wants to fall back to Mi.",
    colorGradient: getCSSVar("solfege-fa-major-gradient"),
    colorPrimary: getCSSVar("solfege-fa-major-primary"),
    colorSecondary: getCSSVar("solfege-fa-major-secondary"),
    colorAccent: getCSSVar("solfege-fa-major-accent"),
    colorHighlight: getCSSVar("solfege-fa-major-highlight"),
    colorFlecks: getCSSVar("solfege-fa-major-flecks"),
    fleckShape: "diamond",
    texture: "inward pull, leaning fall, yearning",
  },
  {
    name: "Sol",
    number: 5,
    emotion: "Strength, confidence, dominance",
    description: "Confident and stable, but not quite home.",
    colorGradient: getCSSVar("solfege-sol-major-gradient"),
    colorPrimary: getCSSVar("solfege-sol-major-primary"),
    colorSecondary: getCSSVar("solfege-sol-major-secondary"),
    colorAccent: getCSSVar("solfege-sol-major-accent"),
    colorHighlight: getCSSVar("solfege-sol-major-highlight"),
    colorFlecks: getCSSVar("solfege-sol-major-flecks"),
    fleckShape: "star",
    texture: "a triumphant beacon",
  },
  {
    name: "La",
    number: 6,
    emotion: "Longing, wistfulness",
    description: "Beautiful sadness, reaching for Do.",
    colorGradient: getCSSVar("solfege-la-major-gradient"),
    colorPrimary: getCSSVar("solfege-la-major-primary"),
    colorSecondary: getCSSVar("solfege-la-major-secondary"),
    colorAccent: getCSSVar("solfege-la-major-accent"),
    colorHighlight: getCSSVar("solfege-la-major-highlight"),
    colorFlecks: getCSSVar("solfege-la-major-flecks"),
    fleckShape: "circle",
    texture: "emotional openness, romantic ache",
  },
  {
    name: "Ti",
    number: 7,
    emotion: "Urgency, restlessness",
    description: "Restless, must resolve up to Do!",
    colorGradient: getCSSVar("solfege-ti-major-gradient"),
    colorPrimary: getCSSVar("solfege-ti-major-primary"),
    colorSecondary: getCSSVar("solfege-ti-major-secondary"),
    colorAccent: getCSSVar("solfege-ti-major-accent"),
    colorHighlight: getCSSVar("solfege-ti-major-highlight"),
    colorFlecks: getCSSVar("solfege-ti-major-flecks"),
    fleckShape: "sparkle",
    texture: "spiritual tension, strong upward pull",
  },
  {
    name: "Do'",
    number: 8,
    emotion: "Resolution, completion",
    description: "Octave completion, return home at higher level",
    colorGradient: getCSSVar("solfege-do-octave-major-gradient"),
    colorPrimary: getCSSVar("solfege-do-octave-major-primary"),
    colorSecondary: getCSSVar("solfege-do-octave-major-secondary"),
    colorAccent: getCSSVar("solfege-do-octave-major-accent"),
    colorHighlight: getCSSVar("solfege-do-octave-major-highlight"),
    colorFlecks: getCSSVar("solfege-do-octave-major-flecks"),
    fleckShape: "star",
    texture: "elevated foundation, triumphant return",
  },
];

// Minor scale solfege data (using movable Do system)
export const MINOR_SOLFEGE: SolfegeData[] = [
  {
    name: "Do",
    number: 1,
    emotion: "Grounded, somber home",
    description: "Dark but stable foundation.",
    colorGradient: getCSSVar("solfege-do-minor-gradient"),
    colorPrimary: getCSSVar("solfege-do-minor-primary"),
    colorSecondary: getCSSVar("solfege-do-minor-secondary"),
    colorAccent: getCSSVar("solfege-do-minor-accent"),
    colorHighlight: getCSSVar("solfege-do-minor-highlight"),
    colorFlecks: getCSSVar("solfege-do-minor-flecks"),
    fleckShape: "circle",
    texture: "dignified stability with emotional weight",
  },
  {
    name: "Re",
    number: 2,
    emotion: "Gentle, uncertain step",
    description: "Cautious movement forward.",
    colorGradient: getCSSVar("solfege-re-minor-gradient"),
    colorPrimary: getCSSVar("solfege-re-minor-primary"),
    colorSecondary: getCSSVar("solfege-re-minor-secondary"),
    colorAccent: getCSSVar("solfege-re-minor-accent"),
    colorHighlight: getCSSVar("solfege-re-minor-highlight"),
    colorFlecks: getCSSVar("solfege-re-minor-flecks"),
    fleckShape: "mist",
    texture: "cautious, introverted motion",
  },
  {
    name: "Me",
    number: 3,
    emotion: "Melancholy, introspection",
    description: "Minor third - tender sadness.",
    colorGradient: getCSSVar("solfege-me-minor-gradient"),
    colorPrimary: getCSSVar("solfege-me-minor-primary"),
    colorSecondary: getCSSVar("solfege-me-minor-secondary"),
    colorAccent: getCSSVar("solfege-me-minor-accent"),
    colorHighlight: getCSSVar("solfege-me-minor-highlight"),
    colorFlecks: getCSSVar("solfege-me-minor-flecks"),
    fleckShape: "diamond",
    texture: "tender vulnerability",
  },
  {
    name: "Fa",
    number: 4,
    emotion: "Tension, yearning",
    description: "Same tension, deeper in minor.",
    colorGradient: getCSSVar("solfege-fa-minor-gradient"),
    colorPrimary: getCSSVar("solfege-fa-minor-primary"),
    colorSecondary: getCSSVar("solfege-fa-minor-secondary"),
    colorAccent: getCSSVar("solfege-fa-minor-accent"),
    colorHighlight: getCSSVar("solfege-fa-minor-highlight"),
    colorFlecks: getCSSVar("solfege-fa-minor-flecks"),
    fleckShape: "circle",
    texture: "a shadowed inward pull",
  },
  {
    name: "Sol",
    number: 5,
    emotion: "Bittersweet strength",
    description: "Strong but tinged with sadness.",
    colorGradient: getCSSVar("solfege-sol-minor-gradient"),
    colorPrimary: getCSSVar("solfege-sol-minor-primary"),
    colorSecondary: getCSSVar("solfege-sol-minor-secondary"),
    colorAccent: getCSSVar("solfege-sol-minor-accent"),
    colorHighlight: getCSSVar("solfege-sol-minor-highlight"),
    colorFlecks: getCSSVar("solfege-sol-minor-flecks"),
    fleckShape: "star",
    texture: "noble sorrow with resilience",
  },
  {
    name: "Le",
    number: 6,
    emotion: "Deep longing, sorrow",
    description: "Minor sixth - profound yearning.",
    colorGradient: getCSSVar("solfege-le-minor-gradient"),
    colorPrimary: getCSSVar("solfege-le-minor-primary"),
    colorSecondary: getCSSVar("solfege-le-minor-secondary"),
    colorAccent: getCSSVar("solfege-le-minor-accent"),
    colorHighlight: getCSSVar("solfege-le-minor-highlight"),
    colorFlecks: getCSSVar("solfege-le-minor-flecks"),
    fleckShape: "mist",
    texture: "grounded grief, ancient ache",
  },
  {
    name: "Te",
    number: 7,
    emotion: "Gentle leading, subdued",
    description: "Softer leading tone than Ti.",
    colorGradient: getCSSVar("solfege-te-minor-gradient"),
    colorPrimary: getCSSVar("solfege-te-minor-primary"),
    colorSecondary: getCSSVar("solfege-te-minor-secondary"),
    colorAccent: getCSSVar("solfege-te-minor-accent"),
    colorHighlight: getCSSVar("solfege-te-minor-highlight"),
    colorFlecks: getCSSVar("solfege-te-minor-flecks"),
    fleckShape: "sparkle",
    texture: "shadowed anticipation",
  },
  {
    name: "Do'",
    number: 8,
    emotion: "Somber resolution, completion",
    description: "Octave completion in minor - dignified return",
    colorGradient: getCSSVar("solfege-do-octave-minor-gradient"),
    colorPrimary: getCSSVar("solfege-do-octave-minor-primary"),
    colorSecondary: getCSSVar("solfege-do-octave-minor-secondary"),
    colorAccent: getCSSVar("solfege-do-octave-minor-accent"),
    colorHighlight: getCSSVar("solfege-do-octave-minor-highlight"),
    colorFlecks: getCSSVar("solfege-do-octave-minor-flecks"),
    fleckShape: "star",
    texture: "elevated dignified stability with emotional depth",
  },
];

// Scale definitions
export const MAJOR_SCALE: Scale = {
  name: "Major",
  intervals: [0, 2, 4, 5, 7, 9, 11, 12], // W-W-H-W-W-W-H pattern + octave
  solfege: MAJOR_SOLFEGE,
};

export const MINOR_SCALE: Scale = {
  name: "Minor",
  intervals: [0, 2, 3, 5, 7, 8, 10, 12], // W-H-W-W-H-W-W pattern (natural minor) + octave
  solfege: MINOR_SOLFEGE,
};

// Common melodic patterns and intervals
export const MELODIC_PATTERNS: MelodicPattern[] = [
  // Emotional Character of Intervals
  {
    name: "Unison/Octave",
    description: "Unity, completion",
    emotion: "Unity, completion",
    sequence: ["Do", "Do"],
    intervals: [0],
  },
  {
    name: "Minor 2nd",
    description: "Dissonance, yearning, pain",
    emotion: "Dissonance, yearning, pain",
    sequence: ["Do", "Re"],
    intervals: [1],
  },
  {
    name: "Major 2nd",
    description: "Gentle tension, stepping forward",
    emotion: "Gentle tension, stepping forward",
    sequence: ["Do", "Re"],
    intervals: [2],
  },
  {
    name: "Minor 3rd",
    description: "Sadness, introspection",
    emotion: "Sadness, introspection",
    sequence: ["Do", "Me"],
    intervals: [3],
  },
  {
    name: "Major 3rd",
    description: "Joy, brightness",
    emotion: "Joy, brightness",
    sequence: ["Do", "Mi"],
    intervals: [4],
  },
  {
    name: "Perfect 4th",
    description: "Stability, openness",
    emotion: "Stability, openness",
    sequence: ["Do", "Fa"],
    intervals: [5],
  },
  {
    name: "Tritone",
    description: "Tension, mystery, unrest",
    emotion: "Tension, mystery, unrest",
    sequence: ["Do", "Fi"],
    intervals: [6],
  },
  {
    name: "Perfect 5th",
    description: "Power, openness, clarity",
    emotion: "Power, openness, clarity",
    sequence: ["Do", "Sol"],
    intervals: [7],
  },
  // Common Melodic Patterns
  {
    name: "Scale Ascent",
    description: "The classic scale journey up",
    emotion: "Rising, building energy",
    sequence: ["Do", "Re", "Mi", "Fa", "Sol", "La", "Ti", "Do"],
  },
  {
    name: "Scale Descent",
    description: "The classic scale journey down",
    emotion: "Falling, releasing energy",
    sequence: ["Do", "Ti", "La", "Sol", "Fa", "Mi", "Re", "Do"],
  },
  {
    name: "Do-Sol-Do",
    description: "Perfect fifth leap, triumphant",
    emotion: "Triumphant, powerful",
    sequence: ["Do", "Sol", "Do"],
  },
  {
    name: "Do-Ti-Do",
    description: "Leading tone resolution, urgent",
    emotion: "Urgent resolution",
    sequence: ["Do", "Ti", "Do"],
  },
  {
    name: "Do-La-Sol",
    description: "Descending sadness",
    emotion: "Melancholic descent",
    sequence: ["Do", "La", "Sol"],
  },
  {
    name: "Sol-Ti-Do",
    description: "Dominant resolution, satisfying",
    emotion: "Satisfying resolution",
    sequence: ["Sol", "Ti", "Do"],
  },
  {
    name: "La-Ti-Do",
    description: "Longing to resolution",
    emotion: "Yearning to home",
    sequence: ["La", "Ti", "Do"],
  },
  {
    name: "Do-Mi-Sol",
    description: "Major triad, bright and stable",
    emotion: "Bright, stable harmony",
    sequence: ["Do", "Mi", "Sol"],
  },
  {
    name: "Do-Re-Mi",
    description: "Optimistic ascent",
    emotion: "Optimistic, rising",
    sequence: ["Do", "Re", "Mi"],
  },
  {
    name: "Mi-Re-Do",
    description: "Gentle descent home",
    emotion: "Gentle return",
    sequence: ["Mi", "Re", "Do"],
  },
  {
    name: "Fa-Mi",
    description: "Tension release, sigh",
    emotion: "Relief, sighing",
    sequence: ["Fa", "Mi"],
  },
  {
    name: "Ti-Do-Ti-Do",
    description: "Restless resolution",
    emotion: "Restless, unsettled",
    sequence: ["Ti", "Do", "Ti", "Do"],
  },
];
