/**
 * The debt baseline: for each design-law rule, how many violations each file had
 * when the lint landed (lint/designLawBaseline.json, generated by
 * `bun run lint:baseline`). A listed file may have at most that many; more fails,
 * and fewer also fails until the baseline is lowered, so counts only go down.
 * `DESIGN_LAW_NO_ALLOWLIST=1` zeroes every budget to list all remaining debt.
 */
import { readFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const BASELINE_FILE = resolve(REPO_ROOT, "lint/designLawBaseline.json");

/** The baseline keys; the Stylelint rules count under the `style/` ones. */
export const RULES = [
  "no-store-imports",
  "no-production-service-imports",
  "no-brand-colour",
  "no-raw-colour",
  "style/no-brand-colour",
  "style/no-raw-colour",
];

let cached;
export function readBaseline() {
  cached ??= JSON.parse(readFileSync(BASELINE_FILE, "utf8"));
  return cached;
}

/** Repo-relative, forward-slash path. */
export const relativeToRoot = (file) => relative(REPO_ROOT, file).split(sep).join("/");

export function budgetFor(rule, file) {
  if (process.env.DESIGN_LAW_NO_ALLOWLIST) return 0;
  return readBaseline()[rule]?.[relativeToRoot(file)] ?? 0;
}

/**
 * Applies a file's budget to what a rule found.
 * Returns the list of problems to report: every occurrence when the file is over
 * budget, one "stale" problem when it is under, nothing when it matches.
 */
export function judge(rule, file, count) {
  const budget = budgetFor(rule, file);
  if (count === budget) return { kind: "ok", budget };
  return { kind: count > budget ? (budget === 0 ? "violation" : "grown") : "stale", budget };
}
