import type { StageLabDirection, StageLabUnit } from "@/types/stageLab";

/*
 * The Stage lab registry: every part of the Stage is its own unit. A unit's
 * strip shows only that part (every other part is soloed out), production
 * first. Blobs, Connections and Lettering are the Note Bodies group:
 * independent parts that work together. Compose combines any picks.
 *
 * A–C in the first four units came from the first round's three families
 * (light, paper, dot-matrix); D–F are new ideas for that part alone.
 */

const fits = (role: StageLabDirection["bible"]["role"], note: string): StageLabDirection["bible"] =>
  ({ zone: "Playing zone", role, fit: "fits", note });
const caution = (role: StageLabDirection["bible"]["role"], note: string): StageLabDirection["bible"] =>
  ({ zone: "Playing zone", role, fit: "caution", note });

export const STAGE_LAB_UNITS: StageLabUnit[] = [
  {
    id: "atmosphere",
    name: "Atmosphere",
    source: "composables/canvas/useAmbientRenderer.ts",
    reading:
      "The ground. Production fills pure black, lays a radial Music Color wash (tonic, sounding pitch, support) and sprinkles random grain. It breathes slowly in silence and follows the envelope with sound; on a phone it reads as almost nothing.",
    keeps: "The clock: the silence breath handing over to the shared envelope, and its place beneath everything.",
    directions: [
      { id: "graticule", letter: "A", name: "Graticule", paper: "cobalt",
        idea: "Ink ground and a scope reticle centred on the scope; only the reticle's edge-light, tinted by the sounding pitch, breathes and brightens.",
        better: "Ink replaces #000 and the Stage gains an instrument face without decoration.",
        risks: "A permanent cross-hair drawn on the Stage.",
        bible: fits("Chassis display", "Chassis lines; light answers sound.") },
      { id: "band", letter: "B", name: "Highlight Band", paper: "tomato",
        idea: "One tilted flat band behind the scope: Ink-3 paper in silence, the sounding pitch's deep colour once it plays.",
        better: "The poster's highlight band, flat instead of a gradient.",
        risks: "A big colour field behind everything; the ground reads as paper.",
        bible: caution("Applied paper", "Music Color only, but the ground becomes pasted paper.") },
      { id: "panel", letter: "C", name: "Unlit Panel", paper: "pine",
        idea: "A dot-matrix panel of unlit LEDs; the backlight steps from Ink-3 to Ink-4 with the envelope.",
        better: "A digital ground that pairs with dot-matrix parts.",
        risks: "Full-Stage texture competes with everything above it.",
        bible: fits("Chassis display", "Two backlight steps, no gradient.") },
      { id: "spotlight", letter: "D", name: "Spotlight", paper: "mustard",
        idea: "A jazz-club spot: one hard-edged cone from above onto the scope in the sounding pitch's deep colour, opening with the envelope. Silence is a dim Ink house light.",
        better: "The Stage becomes a stage. The light has a source and a target: the music is what it lights.",
        risks: "A big shape on a phone; it points at the scope even when bodies are the interest.",
        bible: fits("Light", "Light answers sound; flat, hard-edged.") },
      { id: "tide", letter: "E", name: "Tide Line", paper: "plum",
        idea: "The Stage fills from the deck like a level: a flat floor in the key's tonic colour, its crisp horizon rising with the envelope and settling to a low tide in silence.",
        better: "The ground says where home is (the tonic) and how loud it is, in one shape.",
        risks: "A full-width colour field behind the bodies; the tonic colour never changes within a key.",
        bible: fits("Chassis display", "A level meter the size of the Stage.") },
      { id: "halftone", letter: "F", name: "Halftone", paper: "bone",
        idea: "The production wash printed instead of glowed: a fixed screen of dots in the sounding pitch's colour, largest under the scope and shrinking outward, sized by the envelope.",
        better: "Keeps production's composition (light from the centre) in the poster's print language.",
        risks: "Dot texture can moiré on some screens; it is still a field across the Stage.",
        bible: caution("Applied paper", "Print grammar in Music Color.") },
    ],
  },
  {
    id: "scope",
    name: "Hilbert Scope",
    source: "composables/canvas/useHilbertScopeRenderer.ts",
    reading:
      "The primary musical body: the sound's analytic signal as a glowing loop with a smeared, fading trail, coloured by the first sounding note.",
    keeps: "The Hilbert pair and its mapping, the centre and radius from the Stage solver, and the colour policy.",
    directions: [
      { id: "phosphor", letter: "A", name: "Phosphor", paper: "cobalt",
        idea: "A hot core beam inside its own glow with phosphor persistence that halves every 110ms.",
        better: "Crisper and hotter than the smear; reads as an instrument.",
        risks: "Dense chords tangle into a bright knot.",
        bible: fits("Light", "No blur; light answers sound.") },
      { id: "cut", letter: "B", name: "Paper Cut", paper: "tomato",
        idea: "Twelve times a second the loop is cut out as one flat sheet over an Ink offset; the last three stack and silence peels them away.",
        better: "The waveform as a poster cut-out.",
        risks: "A big flat shape; stepped motion.",
        bible: caution("Applied paper", "Cut grammar in Music Color.") },
      { id: "dots", letter: "C", name: "Dot Trace", paper: "pine",
        idea: "The loop rasterised onto a dot grid; each lit dot decays on its own.",
        better: "A digital edition of the scope.",
        risks: "Coarse at phone pitch.",
        bible: fits("Chassis display", "Only lit dots carry colour.") },
      { id: "groove", letter: "D", name: "Groove", paper: "mustard",
        idea: "The waveform cut into a record: a three-turn spiral groove whose wiggle is the signal, on a label in the pitch's deep colour, turning at 33⅓ only while sound plays.",
        better: "A turntable is the jazz instrument of listening; the scope becomes an object you recognise.",
        risks: "Less of the waveform's shape survives than in a loop; rotation is constant motion while sounding.",
        bible: fits("Chassis display", "Spins only with sound; still in silence.") },
      { id: "brush", letter: "E", name: "Brush", paper: "plum",
        idea: "The loop painted in one calligraphic stroke: a flat nib at a fixed angle makes it thick and thin as the waveform turns. A fresh stroke each frame, no trail.",
        better: "The scope becomes hand-lettering: the poster's hand inside the instrument.",
        risks: "Without a trail it is busier frame to frame; thick strokes can block the bodies.",
        bible: caution("Applied paper", "Hand-made line in Music Color.") },
      { id: "bars", letter: "F", name: "Waveform Bars", paper: "bone",
        idea: "The sound as a level meter you can read: the signal binned into 40 bars across the scope, mirrored about a centre line, with Ivory peak caps that fall slowly.",
        better: "Everyone already reads a waveform; loud and quiet are obvious.",
        risks: "Gives up the Hilbert loop's identity, which is the scope's reason to exist.",
        bible: fits("Chassis display", "A meter: chassis grammar.") },
    ],
  },
  {
    id: "strings",
    name: "Pitch Strings",
    source: "composables/canvas/useStringRenderer.ts",
    reading:
      "Full-height hairlines, one per pitch, in that pitch's colour. The sounding pitch's string vibrates with harmonics and damped ends.",
    keeps: "Which strings exist and where, exact-pitch selection, Presence and Response, and the vibration physics.",
    directions: [
      { id: "exposure", letter: "A", name: "Long Exposure", paper: "cobalt",
        idea: "The envelope of the string's two extremes, faint, with the live string burning inside.",
        better: "Vibration reads as a shape even when still.",
        risks: "Soft light can haze the Stage with many strings.",
        bible: fits("Light", "Light only where a string sounds.") },
      { id: "strips", letter: "B", name: "Torn Strips", paper: "tomato",
        idea: "Ragged paper strips with a lean; a sounding strip thickens, gains an Ink offset and shudders at 12fps.",
        better: "Strings become cut paper like the Keys.",
        risks: "Heavier idle strings; stepped motion.",
        bible: caution("Applied paper", "Cut grammar in Music Color.") },
      { id: "columns", letter: "C", name: "LED Columns", paper: "pine",
        idea: "Columns of lit dots, displaced a whole dot at a time.",
        better: "Quantised like hardware.",
        risks: "Small vibrations vanish below one dot.",
        bible: fits("Chassis display", "Only lit dots carry colour.") },
      { id: "harp", letter: "D", name: "Harp Fan", paper: "mustard",
        idea: "The strings leave the top of the Stage at their own places and converge toward one point at the deck, like a harp's neck to its soundboard.",
        better: "The strings point at where you play; the Stage gains depth.",
        risks: "Strings crowd near the deck and cross the bodies' lower orbit.",
        bible: fits("Chassis display", "An instrument's geometry, coloured only by pitch.") },
      { id: "standing", letter: "E", name: "Standing Waves", paper: "plum",
        idea: "A sounding string shows its mode: filled lobes between nodes, more lobes the higher its register, swapping sides as it vibrates. Idle strings carry node ticks.",
        better: "Teaches how a string actually vibrates, and register becomes visible.",
        risks: "Filled lobes are heavy; the mode number is a simplification of real harmonics.",
        bible: fits("Light", "Physics made visible; only sounding strings fill.") },
      { id: "stave", letter: "F", name: "Stave", paper: "bone",
        idea: "The strings turn on their side and become a staff: one horizontal line per pitch, low at the bottom, high at the top, in Ivory ink; the sounding line takes its colour and vibrates.",
        better: "Pitch height becomes vertical height, as in notation and the accepted Stave Code Strip.",
        risks: "Horizontal lines cut across the scope and bodies; the Stage can read as a diagram.",
        bible: fits("Chassis display", "Notation ink; colour only where a pitch sounds.") },
    ],
  },
  {
    id: "blobs",
    name: "Blobs",
    group: "Note Bodies",
    source: "composables/canvas/useBlobRenderer.ts",
    reading:
      "One body per sounding note on the Circle-of-Fifths orbit: a soft, blurred, glowing disc whose contour vibrates. In production the bodies and their Merge/Web are one fused material; here the bodies stand alone.",
    keeps: "Lifecycle, replay, exact-pitch colour, orbit positions, contour vibration and release timing, all from the production body renderer's prepared frames.",
    directions: [
      { id: "facets", letter: "A", name: "Cut Facets", paper: "mustard",
        idea: "A 7–9 sided cut riding the production contour, with flat facet shading and its colour off-register from an Ivory keyline.",
        better: "The faceted Let's Jazz illustration language; no blur.",
        risks: "The keyline is a new outline.",
        bible: caution("Applied paper", "The poster's off-register outline.") },
      { id: "coin", letter: "B", name: "Solfège Coin", paper: "cobalt",
        idea: "The body says which note it is: a flat disc on its own breathing contour with its solfège syllable struck into it in Jazz type, over an Ink offset.",
        better: "Every body names its note, which is the app's whole lesson.",
        risks: "Text on every body competes with the chord lettering; small bodies make small syllables.",
        bible: fits("Applied paper", "Music Color disc, Ink type.") },
      { id: "key", letter: "C", name: "Key Slip", paper: "tomato",
        idea: "The body is the thing you pressed: a leaning cut Key in its pitch colour with a hard Ink offset, sized by its contour's reach.",
        better: "Stage and Keyboard become one material, so the link between pressing and seeing is literal.",
        risks: "Rectangles stack awkwardly when Merge pulls bodies close.",
        bible: fits("Applied paper", "The Keys' own cut grammar.") },
      { id: "rings", letter: "D", name: "Register Rings", paper: "plum",
        idea: "A flat core with one ring per scientific octave (C4 has four), the outer ring riding the contour: high notes are many fine rings, low notes a few wide ones.",
        better: "Register becomes visible, which colour lightness alone hints at.",
        risks: "Many rings on high notes get dense; the count needs learning.",
        bible: fits("Light", "Music Color only; no blur.") },
    ],
  },
  {
    id: "connections",
    name: "Connections · Merge/Web",
    group: "Note Bodies",
    source: "composables/canvas/useBlobFieldRenderer.ts",
    reading:
      "How bodies relate. Production's organic Merge fuses bodies into one gooey shared body; Web joins every analyzed pair with rooted filaments. Production cannot draw them without the bodies (it is one field), so its frame here shows the fused field.",
    keeps: "Which pairs relate (the harmonic analysis), Merge as one connected body and Web as the full graph, and publishing the drawn path so lettering lands on it.",
    directions: [
      { id: "bands", letter: "A", name: "Two-tone Bands", paper: "mustard",
        idea: "Colour meets at a slanted cut, never a blend. Merge pastes bodies together with wide bands; Web tapes each pair with a thin strip.",
        better: "Each member's exact colour stays exact.",
        risks: "Long-range bands read as ball-and-stick.",
        bible: caution("Applied paper", "Cut grammar in Music Color.") },
      { id: "chord-shape", letter: "B", name: "Chord Shape", paper: "cobalt",
        idea: "The Circle of Fifths becomes a dial of twelve stations and the chord is the polygon its notes make on it; Merge fills it with flat deep facets, Web adds the diagonals.",
        better: "Chord quality becomes a silhouette: every major triad the same triangle turned.",
        risks: "Diagrammatic; twelve small labels.",
        bible: fits("Chassis display", "The dial is chassis; only sounding stations carry colour.") },
      { id: "interference", letter: "C", name: "Interference", paper: "plum",
        idea: "Each note rings outward at a rate proportional to its pitch; in Web the crossings are the relationship, in Merge the chord rings as one from its centre.",
        better: "Consonance shown physically.",
        risks: "Constant rings while held; competes with the circular scope.",
        bible: caution("Light", "Sound-driven, but busy.") },
      { id: "ties", letter: "D", name: "String Ties", paper: "pine",
        idea: "Each relationship is a taut string between two bodies that vibrates as roughly as the interval sounds: a fifth barely trembles, a tritone or a second shivers fast and wide.",
        better: "You see consonance and dissonance without reading a label.",
        risks: "Constant trembling while dissonances hold; the roughness table is a simplification.",
        bible: fits("Light", "Motion only while the interval sounds.") },
      { id: "slurs", letter: "E", name: "Slur Arcs", paper: "bone",
        idea: "Relationships are engraved slurs: tapered Ivory crescents bowing away from the Stage centre, taller for wider intervals.",
        better: "Notation's own mark for notes that belong together; pairs with the Stave.",
        risks: "Ivory arcs are bright; wide chords make tall arcs near the Stage edge.",
        bible: fits("Chassis display", "Notation ink, no brand colour.") },
      { id: "stitches", letter: "F", name: "Stitches", paper: "tomato",
        idea: "Bodies are paper sewn together: a running stitch of Ivory thread along each relationship with one cross-stitch per semitone. Merge sews with doubled thread.",
        better: "Handmade, and the interval size is countable.",
        risks: "Counting stitches is slow for big intervals; thread is fine detail on a phone.",
        bible: caution("Applied paper", "Cut-paper craft; crosses carry Music Color.") },
    ],
  },
  {
    id: "lettering",
    name: "Lettering",
    group: "Note Bodies",
    source: "composables/canvas/harmonicTypography.ts",
    reading:
      "The chord as a cut-paper Jazz headline with glyph tilt and hard Ink offsets, an optional emotion phrase, and interval stamps on their connections. Two organic trials (interval inside the filament, text in the Merge joins) were rolled back.",
    keeps: "The analysis and switches (chord, emotion, intervals, Label Strength) and no recurring motion. None of these bend text into a connection.",
    directions: [
      { id: "tape", letter: "A", name: "Label Tape", paper: "mustard",
        idea: "Words are applied paper: the chord in Ink on Ivory tape, emotion on Ink tape, each interval on a small Ivory stamp at its connection's midpoint.",
        better: "Always legible; built from accepted tape and Stamp grammar.",
        risks: "Ivory paper can outshout the scope.",
        bible: fits("Applied paper", "Ink and Ivory paper.") },
      { id: "readout", letter: "B", name: "Readout", paper: "cobalt",
        idea: "The words leave the canvas into one fixed Readout window at the top of the Stage, member pips the only colour.",
        better: "Bodies stay free of text; theory always in one place.",
        risks: "Words sit away from the shapes they describe.",
        bible: fits("Chassis display", "Reuses the Readout recipe.") },
      { id: "lead-sheet", letter: "C", name: "Lead Sheet", paper: "bone",
        idea: "What a jazz player reads: the chord symbol set above the chord like a lead sheet, and each note's solfège sung beneath its body like a lyric.",
        better: "The chord name and the syllables you sing are both on the Stage, where the notes are.",
        risks: "No interval words; syllables under every body add text.",
        bible: fits("Chassis display", "Ivory type only.") },
      { id: "neon", letter: "D", name: "Neon Sign", paper: "plum",
        idea: "The chord as a jazz-club sign: the symbol in tube light of its bass note's colour with an Ivory-hot core, emotion in a smaller Ivory tube. A new chord strikes with one two-step flicker.",
        better: "Jazz club and synth light in one object; the bass note colours the name.",
        risks: "Glow is soft light, close to the blur the pass removes elsewhere.",
        bible: caution("Light", "Lit by sound, but glows.") },
      { id: "roman", letter: "E", name: "Roman Function", paper: "pine",
        idea: "The headline names what the chord does in the key, not what it is called: vi7, V7, I. The chord symbol and key sit under it in small mono; intervals are plain mono figures.",
        better: "Moves the lesson from naming chords to hearing function.",
        risks: "Roman numerals are harder for beginners; borrowed chords produce awkward figures.",
        bible: fits("Chassis display", "Ivory and Ink type only.") },
    ],
  },
  {
    id: "flecks",
    name: "Note Flecks",
    source: "composables/canvas/useParticleSystem.ts",
    reading: "On each attack, Marks from the whole family appear at random places across the Stage in the note's colour, drift a little and fade.",
    keeps: "Attack-driven only, the randomised whole Mark family, and nothing in flight under Reduced Motion.",
    directions: [
      { id: "sparks", letter: "A", name: "Sparks", paper: "cobalt",
        idea: "Marks thrown off the scope's ring, streaking outward and decaying like phosphor.",
        better: "Flecks come from the sound's body.",
        risks: "They cluster at the scope.",
        bible: fits("Light", "Light answers the attack.") },
      { id: "chads", letter: "B", name: "Chads", paper: "tomato",
        idea: "Cut Marks with an Ink offset pop from the scope, tumble and fall off behind the deck; they never fade.",
        better: "Physical and playful.",
        risks: "Falling paper crosses the lettering.",
        bible: caution("Applied paper", "Cut grammar in Music Color.") },
      { id: "pixels", letter: "C", name: "Pixel Marks", paper: "pine",
        idea: "A Mark lights on a dot grid for a moment, then decays.",
        better: "A pixel-font glyph per attack.",
        risks: "Coarse; can read as noise.",
        bible: fits("Chassis display", "Only lit dots carry colour.") },
      { id: "spray", letter: "D", name: "Body Spray", paper: "mustard",
        idea: "Marks burst out of the note's own body, away from the Stage centre, slow and fade: the attack visibly belongs to that note.",
        better: "The fleck tells you which note was just played.",
        risks: "Bodies at the orbit's edge spray toward the Stage edge, partly off screen.",
        bible: fits("Light", "Answers the attack at its source.") },
      { id: "orbit", letter: "E", name: "Orbiters", paper: "plum",
        idea: "An attack's Marks fall into orbit around the scope for a beat, then fly off on their tangent and fade.",
        better: "The attack feeds the primary body, then leaves.",
        risks: "Orbiting marks cross the bodies on the support orbit.",
        bible: caution("Light", "Motion is longer than the attack.") },
      { id: "stamp", letter: "F", name: "Stamp Hit", paper: "bone",
        idea: "One big Mark stamped onto the note's body on the attack with the system's elastic bounce and an Ink offset, then lifting away. One fleck per note.",
        better: "An accent, not confetti: the shared bounce grammar lives on the Stage.",
        risks: "Big stamps over a chord stack up; less sparkle than production.",
        bible: fits("Applied paper", "Stamp paper grammar, Music Color.") },
    ],
  },
];
